### ISSUE TITLE
Organisatie soort is heel belangrijk. Op kunnen filteren en selecteren.

### ISSUE THREAD

**Issue by nicojs** [nicojs/kei-crm#6]
Lijstje van organisatiesoorten wordt nog aangeleverd

**Comment by elimarte** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/THUISW~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/THUISW~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Categorieën |  
-- | --
  |  
Categorie | Subcategorie
WONEN | 1.      Ambulante en/of mobiele woonondersteuning
  | 2.      Residentiële woonondersteuning minderjarigen
  | 3.      Residentiële woonondersteuning meerderjarigen
  | 4.      Pleegzorg
  | 5.      Rechtstreeks toegankelijke hulp
  | 6.      Bijzondere Jeugdzorg
  | 7.    Psychiatrie
WERKEN | 1.      Maatwerkbedrijf
  | 2.    Dagwerking   (Dagcentrum en/of dagbesteding)
  | 3.      Begeleid werk/Vrijwilligerswerk
  | 4.      Arbeidstraject begeleiding (GTB)
  | 5.    Arbeidszorg
SCHOOL | 1.      BuSO
  | 2.      CLB
  | 3.      Centra basiseducatie
WELZIJN | 1.      CAW
  | 2.    JAC
  | 3.      OCMW
  | 4.    GGZ  & psychiatrische hulpverlening
  | 5.      Justitiehuizen - bemiddeling strafzaken
VRIJE   TIJD | 1.      Ondersteuning-trajectbegeleiding
  | 2.      Vrijetijdsaanbod
TRAJECTBEGELEIDING | Algemeen, vb. DOP
JEUGDWERK | 1.      Jeugdorganisatie
  | 2.    Jeugddienst
VOLWASSENENWERK | 1.    Sociaal-culturele   organisaties
  | 2.      Steunpunten & federaties
ANDERE | Niet   te vatten in een van bovenstaande rubrieken, bij omschrijving kan dan het   waarom en belang aangeduid worden



</body>

</html>

**Comment by nicojs** [comment]
Zit erin
